import {
  Activity,
  Anchor,
  Apple,
  Atom,
  Banknote,
  BarChart,
  Bed,
  Bell,
  Bike,
  Bird,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Castle,
  Church,
  CircuitBoard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dna,
  DollarSign,
  Drama,
  Droplet,
  Dumbbell,
  Eye,
  Factory,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Gamepad2,
  Gavel,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Hash,
  Heart,
  Home,
  Infinity,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Orbit,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Pill,
  Pizza,
  Plane,
  Puzzle,
  Quote,
  Rocket,
  Sailboat,
  Scroll,
  Search,
  Server,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Sigma,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sword,
  Swords,
  Syringe,
  Target,
  Telescope,
  Tent,
  Terminal,
  Train,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  User,
  Users,
  Utensils,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  // Expanded set (2026-06-22) — kept 1:1 with backend ICON_VOCABULARY.
  Cat,
  Skull,
  Book,
  Balloon,
  History,
  Tv,
  Dog,
  Rabbit,
  Squirrel,
  Turtle,
  Snail,
  PawPrint,
  Feather,
  Egg,
  Cherry,
  Carrot,
  Wheat,
  Beer,
  Croissant,
  IceCream,
  Bone,
  HeartPulse,
  Smile,
  Frown,
  Ear,
  Hand,
  Radio,
  Clapperboard,
  Podcast,
  Headphones,
  Guitar,
  Piano,
  Drum,
  Theater,
  Speaker,
  Library,
  BookMarked,
  NotebookPen,
  Pencil,
  School,
  BookText,
  Hourglass,
  Timer,
  CalendarDays,
  TrendingDown,
  Award,
  PartyPopper,
  Building,
  Hotel,
  Store,
  Warehouse,
  Fuel,
  Luggage,
  Backpack,
  Pyramid,
  Battery,
  Plug,
  Magnet,
  Beaker,
  TestTube,
  Radar,
  Satellite,
  Gem,
  HardDrive,
  Bluetooth,
  Antenna,
  Sparkle,
  Rainbow,
  Ghost,
  Bomb,
  Dice5,
  Diamond,
  ThumbsUp,
  type LucideIcon,
} from "lucide-react";

// Static resolution for the model's per-entity / per-event / per-conversation icon
// picks. The model chooses ONLY from the backend's ICON_VOCABULARY (a closed,
// curated set; see backend/src/tools.ts), so we import exactly those statically and
// look them up synchronously.
//
// This deliberately REPLACES lucide-react/dynamic everywhere in the app. DynamicIcon
// lazy-imports each icon as its OWN JS chunk, which (a) made a graph/timeline with
// many distinct icons fire one network request PER icon, and (b) forced Vite to emit
// ~1600 per-icon chunks that the PWA service worker then precached on install (the
// real request storm). The whole vocabulary as static imports is a few KB folded into
// the main bundle — zero extra requests, no per-icon chunks to precache.
//
// THIS LIST MIRRORS backend/src/tools.ts ICON_VOCABULARY. Keep them in sync: every
// name here must be in that list and vice versa (there's a test that asserts it).

// kebab name (lucide's canonical key) -> component.
const VOCABULARY: Record<string, LucideIcon> = {
  "user": User,
  "users": Users,
  "crown": Crown,
  "drama": Drama,
  "mic": Mic,
  "music": Music,
  "brush": Brush,
  "palette": Palette,
  "pen-tool": PenTool,
  "camera": Camera,
  "film": Film,
  "gavel": Gavel,
  "graduation-cap": GraduationCap,
  "stethoscope": Stethoscope,
  "atom": Atom,
  "flask-conical": FlaskConical,
  "microscope": Microscope,
  "dna": Dna,
  "brain": Brain,
  "lightbulb": Lightbulb,
  "calculator": Calculator,
  "sigma": Sigma,
  "telescope": Telescope,
  "orbit": Orbit,
  "rocket": Rocket,
  "map-pin": MapPin,
  "landmark": Landmark,
  "building-2": Building2,
  "church": Church,
  "castle": Castle,
  "mountain": Mountain,
  "tree-pine": TreePine,
  "globe": Globe,
  "waves": Waves,
  "tent": Tent,
  "briefcase": Briefcase,
  "factory": Factory,
  "cpu": Cpu,
  "circuit-board": CircuitBoard,
  "server": Server,
  "cog": Cog,
  "banknote": Banknote,
  "shopping-bag": ShoppingBag,
  "book-open": BookOpen,
  "newspaper": Newspaper,
  "scroll": Scroll,
  "trophy": Trophy,
  "medal": Medal,
  "flag": Flag,
  "calendar": Calendar,
  "swords": Swords,
  "sword": Sword,
  "star": Star,
  "heart": Heart,
  "zap": Zap,
  "code": Code,
  "terminal": Terminal,
  "database": Database,
  "cloud": Cloud,
  "smartphone": Smartphone,
  "laptop": Laptop,
  "monitor": Monitor,
  "wifi": Wifi,
  "bot": Bot,
  "bug": Bug,
  "gamepad-2": Gamepad2,
  "keyboard": Keyboard,
  "map": Map,
  "compass": Compass,
  "plane": Plane,
  "car": Car,
  "train": Train,
  "ship": Ship,
  "bike": Bike,
  "anchor": Anchor,
  "sailboat": Sailboat,
  "sun": Sun,
  "moon": Moon,
  "cloud-rain": CloudRain,
  "snowflake": Snowflake,
  "flame": Flame,
  "leaf": Leaf,
  "flower-2": Flower2,
  "trees": Trees,
  "bird": Bird,
  "fish": Fish,
  "sprout": Sprout,
  "droplet": Droplet,
  "wind": Wind,
  "coffee": Coffee,
  "utensils": Utensils,
  "pizza": Pizza,
  "apple": Apple,
  "wine": Wine,
  "cake": Cake,
  "home": Home,
  "bed": Bed,
  "shirt": Shirt,
  "key": Key,
  "lock": Lock,
  "bell": Bell,
  "clock": Clock,
  "gift": Gift,
  "dollar-sign": DollarSign,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  "pie-chart": PieChart,
  "bar-chart": BarChart,
  "coins": Coins,
  "dumbbell": Dumbbell,
  "footprints": Footprints,
  "activity": Activity,
  "pill": Pill,
  "syringe": Syringe,
  "message-circle": MessageCircle,
  "mail": Mail,
  "phone": Phone,
  "megaphone": Megaphone,
  "eye": Eye,
  "search": Search,
  "target": Target,
  "puzzle": Puzzle,
  "sparkles": Sparkles,
  "infinity": Infinity,
  "hash": Hash,
  "quote": Quote,
  "hammer": Hammer,
  "wrench": Wrench,
  "shield": Shield,
  // Expanded set (2026-06-22) — kept 1:1 with backend ICON_VOCABULARY.
  "cat": Cat,
  "skull": Skull,
  "book": Book,
  "balloon": Balloon,
  "history": History,
  "tv": Tv,
  "dog": Dog,
  "rabbit": Rabbit,
  "squirrel": Squirrel,
  "turtle": Turtle,
  "snail": Snail,
  "paw-print": PawPrint,
  "feather": Feather,
  "egg": Egg,
  "cherry": Cherry,
  "carrot": Carrot,
  "wheat": Wheat,
  "beer": Beer,
  "croissant": Croissant,
  "ice-cream": IceCream,
  "bone": Bone,
  "heart-pulse": HeartPulse,
  "smile": Smile,
  "frown": Frown,
  "ear": Ear,
  "hand": Hand,
  "radio": Radio,
  "clapperboard": Clapperboard,
  "podcast": Podcast,
  "headphones": Headphones,
  "guitar": Guitar,
  "piano": Piano,
  "drum": Drum,
  "theater": Theater,
  "speaker": Speaker,
  "library": Library,
  "book-marked": BookMarked,
  "notebook-pen": NotebookPen,
  "pencil": Pencil,
  "school": School,
  "book-text": BookText,
  "hourglass": Hourglass,
  "timer": Timer,
  "calendar-days": CalendarDays,
  "trending-down": TrendingDown,
  "award": Award,
  "party-popper": PartyPopper,
  "building": Building,
  "hotel": Hotel,
  "store": Store,
  "warehouse": Warehouse,
  "fuel": Fuel,
  "luggage": Luggage,
  "backpack": Backpack,
  "pyramid": Pyramid,
  "battery": Battery,
  "plug": Plug,
  "magnet": Magnet,
  "beaker": Beaker,
  "test-tube": TestTube,
  "radar": Radar,
  "satellite": Satellite,
  "gem": Gem,
  "hard-drive": HardDrive,
  "bluetooth": Bluetooth,
  "antenna": Antenna,
  "sparkle": Sparkle,
  "rainbow": Rainbow,
  "ghost": Ghost,
  "bomb": Bomb,
  "dice-5": Dice5,
  "diamond": Diamond,
  "thumbs-up": ThumbsUp,
};

// "FlaskConical" -> "flask-conical", "Building2" -> "building-2". Mirrors lucide's
// kebab-casing (letter->digit boundary also gets a dash), matching the backend names.
function toKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

// The full set of valid kebab names — exported so a test can assert it matches the
// backend ICON_VOCABULARY.
export const VOCABULARY_ICON_NAMES = new Set(Object.keys(VOCABULARY));

// The vocabulary component for a model-suggested name (PascalCase from the wire), or
// null when the model picked a name outside the vocabulary (the caller renders its
// own fallback). O(1) lookup, no dynamic import.
export function resolveVocabularyIcon(icon: string): LucideIcon | null {
  return VOCABULARY[toKebab(icon)] ?? null;
}
