import {
  Activity,
  Anchor,
  Antenna,
  Apple,
  Atom,
  Award,
  Backpack,
  Balloon,
  Banknote,
  BarChart,
  Battery,
  Beaker,
  Bed,
  Beer,
  Bell,
  Bike,
  Bird,
  Bluetooth,
  Bomb,
  Bone,
  Book,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Cake,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Castle,
  // Expanded set (2026-06-22) — kept 1:1 with backend ICON_VOCABULARY.
  Cat,
  Cherry,
  Church,
  CircuitBoard,
  Clapperboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  Database,
  Diamond,
  Dice5,
  Dna,
  Dog,
  DollarSign,
  Drama,
  Droplet,
  Drum,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  Factory,
  Feather,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Hand,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  History,
  Home,
  Hotel,
  Hourglass,
  IceCream,
  Infinity as InfinityIcon,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  type LucideIcon,
  Luggage,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Orbit,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PenTool,
  Phone,
  Piano,
  PieChart,
  Pill,
  Pizza,
  Plane,
  Plug,
  Podcast,
  Puzzle,
  Pyramid,
  Quote,
  Rabbit,
  Radar,
  Radio,
  Rainbow,
  Rocket,
  Sailboat,
  Satellite,
  School,
  Scroll,
  Search,
  Server,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Sigma,
  Skull,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sword,
  Swords,
  Syringe,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  Theater,
  ThumbsUp,
  Timer,
  Train,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Turtle,
  Tv,
  User,
  Users,
  Utensils,
  Warehouse,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

// Static resolution for the model's per-entity / per-event / per-conversation icon
// picks. The model chooses ONLY from the backend's ICON_VOCABULARY (a closed,
// curated set; see backend/src/tools.ts), so we import exactly those statically and
// look them up synchronously.
//
// This deliberately REPLACES lucide-react/dynamic everywhere in the app. DynamicIcon
// lazy-imports each icon as its OWN JS chunk, which (a) made a graph/timeline with
// many distinct icons fire one network request PER icon, and (b) forced Vite to emit
// ~1600 per-icon chunks that the PWA service worker then precached on install (the
// real request storm). The whole vocabulary as static imports is a few KB folded into
// the main bundle — zero extra requests, no per-icon chunks to precache.
//
// THIS LIST MIRRORS backend/src/tools.ts ICON_VOCABULARY. Keep them in sync: every
// name here must be in that list and vice versa (there's a test that asserts it).

// kebab name (lucide's canonical key) -> component.
const VOCABULARY: Record<string, LucideIcon> = {
  user: User,
  users: Users,
  crown: Crown,
  drama: Drama,
  mic: Mic,
  music: Music,
  brush: Brush,
  palette: Palette,
  "pen-tool": PenTool,
  camera: Camera,
  film: Film,
  gavel: Gavel,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  atom: Atom,
  "flask-conical": FlaskConical,
  microscope: Microscope,
  dna: Dna,
  brain: Brain,
  lightbulb: Lightbulb,
  calculator: Calculator,
  sigma: Sigma,
  telescope: Telescope,
  orbit: Orbit,
  rocket: Rocket,
  "map-pin": MapPin,
  landmark: Landmark,
  "building-2": Building2,
  church: Church,
  castle: Castle,
  mountain: Mountain,
  "tree-pine": TreePine,
  globe: Globe,
  waves: Waves,
  tent: Tent,
  briefcase: Briefcase,
  factory: Factory,
  cpu: Cpu,
  "circuit-board": CircuitBoard,
  server: Server,
  cog: Cog,
  banknote: Banknote,
  "shopping-bag": ShoppingBag,
  "book-open": BookOpen,
  newspaper: Newspaper,
  scroll: Scroll,
  trophy: Trophy,
  medal: Medal,
  flag: Flag,
  calendar: Calendar,
  swords: Swords,
  sword: Sword,
  star: Star,
  heart: Heart,
  zap: Zap,
  code: Code,
  terminal: Terminal,
  database: Database,
  cloud: Cloud,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  wifi: Wifi,
  bot: Bot,
  bug: Bug,
  "gamepad-2": Gamepad2,
  keyboard: Keyboard,
  map: MapIcon,
  compass: Compass,
  plane: Plane,
  car: Car,
  train: Train,
  ship: Ship,
  bike: Bike,
  anchor: Anchor,
  sailboat: Sailboat,
  sun: Sun,
  moon: Moon,
  "cloud-rain": CloudRain,
  snowflake: Snowflake,
  flame: Flame,
  leaf: Leaf,
  "flower-2": Flower2,
  trees: Trees,
  bird: Bird,
  fish: Fish,
  sprout: Sprout,
  droplet: Droplet,
  wind: Wind,
  coffee: Coffee,
  utensils: Utensils,
  pizza: Pizza,
  apple: Apple,
  wine: Wine,
  cake: Cake,
  home: Home,
  bed: Bed,
  shirt: Shirt,
  key: Key,
  lock: Lock,
  bell: Bell,
  clock: Clock,
  gift: Gift,
  "dollar-sign": DollarSign,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  "pie-chart": PieChart,
  "bar-chart": BarChart,
  coins: Coins,
  dumbbell: Dumbbell,
  footprints: Footprints,
  activity: Activity,
  pill: Pill,
  syringe: Syringe,
  "message-circle": MessageCircle,
  mail: Mail,
  phone: Phone,
  megaphone: Megaphone,
  eye: Eye,
  search: Search,
  target: Target,
  puzzle: Puzzle,
  sparkles: Sparkles,
  infinity: InfinityIcon,
  hash: Hash,
  quote: Quote,
  hammer: Hammer,
  wrench: Wrench,
  shield: Shield,
  // Expanded set (2026-06-22) — kept 1:1 with backend ICON_VOCABULARY.
  cat: Cat,
  skull: Skull,
  book: Book,
  balloon: Balloon,
  history: History,
  tv: Tv,
  dog: Dog,
  rabbit: Rabbit,
  squirrel: Squirrel,
  turtle: Turtle,
  snail: Snail,
  "paw-print": PawPrint,
  feather: Feather,
  egg: Egg,
  cherry: Cherry,
  carrot: Carrot,
  wheat: Wheat,
  beer: Beer,
  croissant: Croissant,
  "ice-cream": IceCream,
  bone: Bone,
  "heart-pulse": HeartPulse,
  smile: Smile,
  frown: Frown,
  ear: Ear,
  hand: Hand,
  radio: Radio,
  clapperboard: Clapperboard,
  podcast: Podcast,
  headphones: Headphones,
  guitar: Guitar,
  piano: Piano,
  drum: Drum,
  theater: Theater,
  speaker: Speaker,
  library: Library,
  "book-marked": BookMarked,
  "notebook-pen": NotebookPen,
  pencil: Pencil,
  school: School,
  "book-text": BookText,
  hourglass: Hourglass,
  timer: Timer,
  "calendar-days": CalendarDays,
  "trending-down": TrendingDown,
  award: Award,
  "party-popper": PartyPopper,
  building: Building,
  hotel: Hotel,
  store: Store,
  warehouse: Warehouse,
  fuel: Fuel,
  luggage: Luggage,
  backpack: Backpack,
  pyramid: Pyramid,
  battery: Battery,
  plug: Plug,
  magnet: Magnet,
  beaker: Beaker,
  "test-tube": TestTube,
  radar: Radar,
  satellite: Satellite,
  gem: Gem,
  "hard-drive": HardDrive,
  bluetooth: Bluetooth,
  antenna: Antenna,
  sparkle: Sparkle,
  rainbow: Rainbow,
  ghost: Ghost,
  bomb: Bomb,
  "dice-5": Dice5,
  diamond: Diamond,
  "thumbs-up": ThumbsUp,
};

// "FlaskConical" -> "flask-conical", "Building2" -> "building-2". Mirrors lucide's
// kebab-casing (letter->digit boundary also gets a dash), matching the backend names.
function toKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

// The full set of valid kebab names — exported so a test can assert it matches the
// backend ICON_VOCABULARY.
export const VOCABULARY_ICON_NAMES = new Set(Object.keys(VOCABULARY));

// The vocabulary component for a model-suggested name (PascalCase from the wire), or
// null when the model picked a name outside the vocabulary (the caller renders its
// own fallback). O(1) lookup, no dynamic import.
export function resolveVocabularyIcon(icon: string): LucideIcon | null {
  return VOCABULARY[toKebab(icon)] ?? null;
}
